trainingInput:
#  https://cloud.google.com/ml-engine/docs/tensorflow/training-overview
  scaleTier: CUSTOM #BASIC
  masterType: complex_model_l_gpu #complex_model_l_gpu #large_model #complex_model_l
  workerType: complex_model_l_gpu #complex_model_l_gpu #large_model #complex_model_l
  parameterServerType: complex_model_l_gpu #complex_model_l_gpu #large_model
  workerCount: 1
  parameterServerCount: 1
  pythonVersion: '3.5'